## Importing data:

In [1]:
import polars as pl
import gc

train_path = '/kaggle/input/competitions/cyber-physical-anomaly-detection-for-der-systems/train.csv'

train_df = pl.read_csv(train_path)
print('Training set: ', train_df.shape)
display(train_df.head(3))

Training set:  (2363163, 725)

shape: (3, 725)
┌─────────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────┐
│ Id      ┆ common[0]. ┆ common[0]. ┆ common[0]. ┆ … ┆ DERMeasure ┆ DERMeasure ┆ DERMeasur ┆ Label │
│ ---     ┆ ID         ┆ L          ┆ Mn         ┆   ┆ DC[0].Prt[ ┆ DC[0].Prt[ ┆ eDC[0].Pr ┆ ---   │
│ i64     ┆ ---        ┆ ---        ┆ ---        ┆   ┆ 1].DCWhInj ┆ 1].DCWhAbs ┆ t[1].Tmp  ┆ i64   │
│         ┆ f64        ┆ f64        ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---       ┆       │
│         ┆            ┆            ┆            ┆   ┆ str        ┆ str        ┆ f64       ┆       │
╞═════════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════╡
│ 477210  ┆ 1.0        ┆ 66.0       ┆ DERSec     ┆ … ┆ null       ┆ null       ┆ 23.0      ┆ 1     │
│ 2527629 ┆ 1.0        ┆ 66.0       ┆ DERSec     ┆ … ┆ null       ┆ null       ┆ 23.0      ┆ 1     │
│ 1159927 ┆ 1.0        ┆ 66.0       ┆ DERSec     ┆ … ┆ null       ┆ null       ┆ 23.0      ┆ 0     │
└─────────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────┘

In [2]:
print('Total number of datapoints/samples in training set: ', len(train_df))

Total number of datapoints/samples in training set:  2363163

In [3]:
#Finding number of unique values in each column
unique_dict = {col:train_df[col].n_unique() for col in train_df.columns}

#removing redundant columns
unique_count_1_cols = [col for col,count in unique_dict.items() if count==1]
train_df = train_df.drop(unique_count_1_cols)
print(f"Dropped a total of {len(unique_count_1_cols)} columns \n")
print("Dropped columns:", unique_count_1_cols)

Dropped a total of 262 columns

Dropped columns: ['common[0].DA', 'DERMeasureAC[0].TotWhInj', 'DERMeasureAC[0].TotWhAbs', 'DERMeasureAC[0].TotVarhInj', 'DERMeasureAC[0].TotVarhAbs', 'DERMeasureAC[0].TotWhInjL1', 'DERMeasureAC[0].TotWhAbsL1', 'DERMeasureAC[0].TotVarhInjL1', 'DERMeasureAC[0].TotVarhAbsL1', 'DERMeasureAC[0].TotWhInjL2', 'DERMeasureAC[0].TotWhAbsL2', 'DERMeasureAC[0].TotVarhInjL2', 'DERMeasureAC[0].TotVarhAbsL2', 'DERMeasureAC[0].TotWhInjL3', 'DERMeasureAC[0].TotWhAbsL3', 'DERMeasureAC[0].TotVarhInjL3', 'DERMeasureAC[0].TotVarhAbsL3', 'DERMeasureAC[0].PF_SF', 'DERMeasureAC[0].TotWh_SF', 'DERMeasureAC[0].TotVarh_SF', 'DERMeasureAC[0].Tmp_SF', 'DERCapacity[0].WDisChaRteMaxRtg', 'DERCapacity[0].VADisChaRteMaxRtg', 'DERCapacity[0].PFOvrExtRtg', 'DERCapacity[0].PFUndExtRtg', 'DERCapacity[0].VMax', 'DERCapacity[0].VMin', 'DERCapacity[0].PFOvrExt', 'DERCapacity[0].PFUndExt', 'DERCapacity[0].PF_SF', 'DERCapacity[0].S_SF', 'DEREnterService[0].ESDlyRemTms', 'DERCtlAC[0].PFWInjRvrtTms', 'DERCtlAC[0].PFWInjRvrtRem', 'DERCtlAC[0].PFWAbsRvrtTms', 'DERCtlAC[0].PFWAbsRvrtRem', 'DERCtlAC[0].WMaxLimPctRvrt', 'DERCtlAC[0].WMaxLimPctRvrtTms', 'DERCtlAC[0].WMaxLimPctRvrtRem', 'DERCtlAC[0].WSetRvrt', 'DERCtlAC[0].WSetPctRvrt', 'DERCtlAC[0].WSetRvrtTms', 'DERCtlAC[0].WSetRvrtRem', 'DERCtlAC[0].VarSetRvrtTms', 'DERCtlAC[0].VarSetRvrtRem', 'DERCtlAC[0].WRmp', 'DERCtlAC[0].VarRmp', 'DERCtlAC[0].WSetPct_SF', 'DERCtlAC[0].VarSet_SF', 'DERCtlAC[0].PFWInjRvrt.PF', 'DERCtlAC[0].PFWAbs.PF', 'DERCtlAC[0].PFWAbsRvrt.PF', 'DERVoltVar[0].RvrtTms', 'DERVoltVar[0].RvrtRem', 'DERVoltVar[0].RvrtCrv', 'DERVoltVar[0].Crv[0].VRefAuto', 'DERVoltVar[0].Crv[1].VRefAuto', 'DERVoltVar[0].Crv[2].VRefAuto', 'DERVoltWatt[0].RvrtTms', 'DERVoltWatt[0].RvrtRem', 'DERVoltWatt[0].RvrtCrv', 'DERTripLV[0].Crv[0].MayTrip.ActPt', 'DERTripLV[0].Crv[0].MayTrip.Pt[0].V', 'DERTripLV[0].Crv[0].MayTrip.Pt[0].Tms', 'DERTripLV[0].Crv[0].MayTrip.Pt[1].V', 'DERTripLV[0].Crv[0].MayTrip.Pt[1].Tms', 'DERTripLV[0].Crv[0].MayTrip.Pt[2].V', 'DERTripLV[0].Crv[0].MayTrip.Pt[2].Tms', 'DERTripLV[0].Crv[0].MayTrip.Pt[3].V', 'DERTripLV[0].Crv[0].MayTrip.Pt[3].Tms', 'DERTripLV[0].Crv[0].MayTrip.Pt[4].V', 'DERTripLV[0].Crv[0].MayTrip.Pt[4].Tms', 'DERTripLV[0].Crv[0].MomCess.ActPt', 'DERTripLV[0].Crv[0].MomCess.Pt[0].V', 'DERTripLV[0].Crv[0].MomCess.Pt[0].Tms', 'DERTripLV[0].Crv[0].MomCess.Pt[1].V', 'DERTripLV[0].Crv[0].MomCess.Pt[1].Tms', 'DERTripLV[0].Crv[0].MomCess.Pt[2].V', 'DERTripLV[0].Crv[0].MomCess.Pt[2].Tms', 'DERTripLV[0].Crv[0].MomCess.Pt[3].V', 'DERTripLV[0].Crv[0].MomCess.Pt[3].Tms', 'DERTripLV[0].Crv[0].MomCess.Pt[4].V', 'DERTripLV[0].Crv[0].MomCess.Pt[4].Tms', 'DERTripLV[0].Crv[1].MayTrip.ActPt', 'DERTripLV[0].Crv[1].MayTrip.Pt[0].V', 'DERTripLV[0].Crv[1].MayTrip.Pt[0].Tms', 'DERTripLV[0].Crv[1].MayTrip.Pt[1].V', 'DERTripLV[0].Crv[1].MayTrip.Pt[1].Tms', 'DERTripLV[0].Crv[1].MayTrip.Pt[2].V', 'DERTripLV[0].Crv[1].MayTrip.Pt[2].Tms', 'DERTripLV[0].Crv[1].MayTrip.Pt[3].V', 'DERTripLV[0].Crv[1].MayTrip.Pt[3].Tms', 'DERTripLV[0].Crv[1].MayTrip.Pt[4].V', 'DERTripLV[0].Crv[1].MayTrip.Pt[4].Tms', 'DERTripLV[0].Crv[1].MomCess.ActPt', 'DERTripLV[0].Crv[1].MomCess.Pt[0].V', 'DERTripLV[0].Crv[1].MomCess.Pt[0].Tms', 'DERTripLV[0].Crv[1].MomCess.Pt[1].V', 'DERTripLV[0].Crv[1].MomCess.Pt[1].Tms', 'DERTripLV[0].Crv[1].MomCess.Pt[2].V', 'DERTripLV[0].Crv[1].MomCess.Pt[2].Tms', 'DERTripLV[0].Crv[1].MomCess.Pt[3].V', 'DERTripLV[0].Crv[1].MomCess.Pt[3].Tms', 'DERTripLV[0].Crv[1].MomCess.Pt[4].V', 'DERTripLV[0].Crv[1].MomCess.Pt[4].Tms', 'DERTripHV[0].Crv[0].MayTrip.ActPt', 'DERTripHV[0].Crv[0].MayTrip.Pt[0].V', 'DERTripHV[0].Crv[0].MayTrip.Pt[0].Tms', 'DERTripHV[0].Crv[0].MayTrip.Pt[1].V', 'DERTripHV[0].Crv[0].MayTrip.Pt[1].Tms', 'DERTripHV[0].Crv[0].MayTrip.Pt[2].V', 'DERTripHV[0].Crv[0].MayTrip.Pt[2].Tms', 'DERTripHV[0].Crv[0].MayTrip.Pt[3].V', 'DERTripHV[0].Crv[0].MayTrip.Pt[3].Tms', 'DERTripHV[0].Crv[0].MayTrip.Pt[4].V', 'DERTripHV[0].Crv[0].MayTrip.Pt[4].Tms', 'DERTripHV[0].Crv[0].MomCess.ActPt', 'DERTripHV[0].Crv[0].MomCess.Pt[0].V', 'DERTripHV[0].Crv[0].MomCess.Pt[0].Tms', 'DERTripHV[0].Crv[0].MomCess.Pt[1].V', 'DERTripHV[0].Crv[0].MomCess.Pt[1].Tms', 'DERTripHV[0].Crv[0].MomCess.Pt[2].V', 'DERTripHV[0].Crv[0].MomCess.Pt[2].Tms', 'DERTripHV[0].Crv[0].MomCess.Pt[3].V', 'DERTripHV[0].Crv[0].MomCess.Pt[3].Tms', 'DERTripHV[0].Crv[0].MomCess.Pt[4].V', 'DERTripHV[0].Crv[0].MomCess.Pt[4].Tms', 'DERTripHV[0].Crv[1].MayTrip.ActPt', 'DERTripHV[0].Crv[1].MayTrip.Pt[0].V', 'DERTripHV[0].Crv[1].MayTrip.Pt[0].Tms', 'DERTripHV[0].Crv[1].MayTrip.Pt[1].V', 'DERTripHV[0].Crv[1].MayTrip.Pt[1].Tms', 'DERTripHV[0].Crv[1].MayTrip.Pt[2].V', 'DERTripHV[0].Crv[1].MayTrip.Pt[2].Tms', 'DERTripHV[0].Crv[1].MayTrip.Pt[3].V', 'DERTripHV[0].Crv[1].MayTrip.Pt[3].Tms', 'DERTripHV[0].Crv[1].MayTrip.Pt[4].V', 'DERTripHV[0].Crv[1].MayTrip.Pt[4].Tms', 'DERTripHV[0].Crv[1].MomCess.ActPt', 'DERTripHV[0].Crv[1].MomCess.Pt[0].V', 'DERTripHV[0].Crv[1].MomCess.Pt[0].Tms', 'DERTripHV[0].Crv[1].MomCess.Pt[1].V', 'DERTripHV[0].Crv[1].MomCess.Pt[1].Tms', 'DERTripHV[0].Crv[1].MomCess.Pt[2].V', 'DERTripHV[0].Crv[1].MomCess.Pt[2].Tms', 'DERTripHV[0].Crv[1].MomCess.Pt[3].V', 'DERTripHV[0].Crv[1].MomCess.Pt[3].Tms', 'DERTripHV[0].Crv[1].MomCess.Pt[4].V', 'DERTripHV[0].Crv[1].MomCess.Pt[4].Tms', 'DERTripLF[0].Crv[0].MayTrip.ActPt', 'DERTripLF[0].Crv[0].MayTrip.Pt[0].Hz', 'DERTripLF[0].Crv[0].MayTrip.Pt[0].Tms', 'DERTripLF[0].Crv[0].MayTrip.Pt[1].Hz', 'DERTripLF[0].Crv[0].MayTrip.Pt[1].Tms', 'DERTripLF[0].Crv[0].MayTrip.Pt[2].Hz', 'DERTripLF[0].Crv[0].MayTrip.Pt[2].Tms', 'DERTripLF[0].Crv[0].MayTrip.Pt[3].Hz', 'DERTripLF[0].Crv[0].MayTrip.Pt[3].Tms', 'DERTripLF[0].Crv[0].MayTrip.Pt[4].Hz', 'DERTripLF[0].Crv[0].MayTrip.Pt[4].Tms', 'DERTripLF[0].Crv[0].MomCess.ActPt', 'DERTripLF[0].Crv[0].MomCess.Pt[0].Hz', 'DERTripLF[0].Crv[0].MomCess.Pt[0].Tms', 'DERTripLF[0].Crv[0].MomCess.Pt[1].Hz', 'DERTripLF[0].Crv[0].MomCess.Pt[1].Tms', 'DERTripLF[0].Crv[0].MomCess.Pt[2].Hz', 'DERTripLF[0].Crv[0].MomCess.Pt[2].Tms', 'DERTripLF[0].Crv[0].MomCess.Pt[3].Hz', 'DERTripLF[0].Crv[0].MomCess.Pt[3].Tms', 'DERTripLF[0].Crv[0].MomCess.Pt[4].Hz', 'DERTripLF[0].Crv[0].MomCess.Pt[4].Tms', 'DERTripLF[0].Crv[1].MayTrip.ActPt', 'DERTripLF[0].Crv[1].MayTrip.Pt[0].Hz', 'DERTripLF[0].Crv[1].MayTrip.Pt[0].Tms', 'DERTripLF[0].Crv[1].MayTrip.Pt[1].Hz', 'DERTripLF[0].Crv[1].MayTrip.Pt[1].Tms', 'DERTripLF[0].Crv[1].MayTrip.Pt[2].Hz', 'DERTripLF[0].Crv[1].MayTrip.Pt[2].Tms', 'DERTripLF[0].Crv[1].MayTrip.Pt[3].Hz', 'DERTripLF[0].Crv[1].MayTrip.Pt[3].Tms', 'DERTripLF[0].Crv[1].MayTrip.Pt[4].Hz', 'DERTripLF[0].Crv[1].MayTrip.Pt[4].Tms', 'DERTripLF[0].Crv[1].MomCess.ActPt', 'DERTripLF[0].Crv[1].MomCess.Pt[0].Hz', 'DERTripLF[0].Crv[1].MomCess.Pt[0].Tms', 'DERTripLF[0].Crv[1].MomCess.Pt[1].Hz', 'DERTripLF[0].Crv[1].MomCess.Pt[1].Tms', 'DERTripLF[0].Crv[1].MomCess.Pt[2].Hz', 'DERTripLF[0].Crv[1].MomCess.Pt[2].Tms', 'DERTripLF[0].Crv[1].MomCess.Pt[3].Hz', 'DERTripLF[0].Crv[1].MomCess.Pt[3].Tms', 'DERTripLF[0].Crv[1].MomCess.Pt[4].Hz', 'DERTripLF[0].Crv[1].MomCess.Pt[4].Tms', 'DERTripHF[0].Crv[0].MayTrip.ActPt', 'DERTripHF[0].Crv[0].MayTrip.Pt[0].Hz', 'DERTripHF[0].Crv[0].MayTrip.Pt[0].Tms', 'DERTripHF[0].Crv[0].MayTrip.Pt[1].Hz', 'DERTripHF[0].Crv[0].MayTrip.Pt[1].Tms', 'DERTripHF[0].Crv[0].MayTrip.Pt[2].Hz', 'DERTripHF[0].Crv[0].MayTrip.Pt[2].Tms', 'DERTripHF[0].Crv[0].MayTrip.Pt[3].Hz', 'DERTripHF[0].Crv[0].MayTrip.Pt[3].Tms', 'DERTripHF[0].Crv[0].MayTrip.Pt[4].Hz', 'DERTripHF[0].Crv[0].MayTrip.Pt[4].Tms', 'DERTripHF[0].Crv[0].MomCess.ActPt', 'DERTripHF[0].Crv[0].MomCess.Pt[0].Hz', 'DERTripHF[0].Crv[0].MomCess.Pt[0].Tms', 'DERTripHF[0].Crv[0].MomCess.Pt[1].Hz', 'DERTripHF[0].Crv[0].MomCess.Pt[1].Tms', 'DERTripHF[0].Crv[0].MomCess.Pt[2].Hz', 'DERTripHF[0].Crv[0].MomCess.Pt[2].Tms', 'DERTripHF[0].Crv[0].MomCess.Pt[3].Hz', 'DERTripHF[0].Crv[0].MomCess.Pt[3].Tms', 'DERTripHF[0].Crv[0].MomCess.Pt[4].Hz', 'DERTripHF[0].Crv[0].MomCess.Pt[4].Tms', 'DERTripHF[0].Crv[1].MayTrip.ActPt', 'DERTripHF[0].Crv[1].MayTrip.Pt[0].Hz', 'DERTripHF[0].Crv[1].MayTrip.Pt[0].Tms', 'DERTripHF[0].Crv[1].MayTrip.Pt[1].Hz', 'DERTripHF[0].Crv[1].MayTrip.Pt[1].Tms', 'DERTripHF[0].Crv[1].MayTrip.Pt[2].Hz', 'DERTripHF[0].Crv[1].MayTrip.Pt[2].Tms', 'DERTripHF[0].Crv[1].MayTrip.Pt[3].Hz', 'DERTripHF[0].Crv[1].MayTrip.Pt[3].Tms', 'DERTripHF[0].Crv[1].MayTrip.Pt[4].Hz', 'DERTripHF[0].Crv[1].MayTrip.Pt[4].Tms', 'DERTripHF[0].Crv[1].MomCess.ActPt', 'DERTripHF[0].Crv[1].MomCess.Pt[0].Hz', 'DERTripHF[0].Crv[1].MomCess.Pt[0].Tms', 'DERTripHF[0].Crv[1].MomCess.Pt[1].Hz', 'DERTripHF[0].Crv[1].MomCess.Pt[1].Tms', 'DERTripHF[0].Crv[1].MomCess.Pt[2].Hz', 'DERTripHF[0].Crv[1].MomCess.Pt[2].Tms', 'DERTripHF[0].Crv[1].MomCess.Pt[3].Hz', 'DERTripHF[0].Crv[1].MomCess.Pt[3].Tms', 'DERTripHF[0].Crv[1].MomCess.Pt[4].Hz', 'DERTripHF[0].Crv[1].MomCess.Pt[4].Tms', 'DERFreqDroop[0].RvrtTms', 'DERFreqDroop[0].RvrtRem', 'DERFreqDroop[0].RvrtCtl', 'DERFreqDroop[0].Ctl[2].PMin', 'DERWattVar[0].RvrtTms', 'DERWattVar[0].RvrtRem', 'DERWattVar[0].RvrtCrv', 'DERMeasureDC[0].ID', 'DERMeasureDC[0].L', 'DERMeasureDC[0].NPrt', 'DERMeasureDC[0].DCWhInj', 'DERMeasureDC[0].DCWhAbs', 'DERMeasureDC[0].DCV_SF', 'DERMeasureDC[0].DCWH_SF', 'DERMeasureDC[0].Tmp_SF', 'DERMeasureDC[0].Prt[0].ID', 'DERMeasureDC[0].Prt[0].IDStr', 'DERMeasureDC[0].Prt[0].DCWhInj', 'DERMeasureDC[0].Prt[0].DCWhAbs', 'DERMeasureDC[0].Prt[0].Tmp', 'DERMeasureDC[0].Prt[1].ID', 'DERMeasureDC[0].Prt[1].IDStr', 'DERMeasureDC[0].Prt[1].DCWhInj', 'DERMeasureDC[0].Prt[1].DCWhAbs', 'DERMeasureDC[0].Prt[1].Tmp']

In [4]:
#Dropping columns with too many null values
cols_to_drop = ['DERCtlAC[0].PFWAbs.Ext','DERCtlAC[0].PFWAbsRvrt.Ext','DERMeasureAC[0].ThrotPct','DERMeasureAC[0].ThrotSrc']
train_df = train_df.drop(cols_to_drop)

#Dropping null values from remaining columns
train_df = train_df.drop_nulls()

In [5]:
#Seprating label and features
X = train_df.drop(['Id','Label'])
y = train_df['Label']

In [6]:
#clearing up memory since the dataset is huge
del train_df
gc.collect()
print("Memory cleared!")

Memory cleared!

## Preprocessing:

In [7]:
cat_cols = X.select(pl.col(pl.Utf8)).columns

In [8]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

cat_pipe = Pipeline([
('encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1))
])

preprocessor = ColumnTransformer(
    transformers=[('cat', cat_pipe, cat_cols)],
    remainder='passthrough'
)

## Optuna tuned XGBoost:

In [9]:
tuned_xgb_params = {'n_estimators': 2382,
                    'learning_rate': 0.036989524346778366,
                    'max_depth': 12,
                    'min_child_weight': 4,
                    'gamma': 2.2246104780594558,
                    'subsample': 0.610932734562846,
                    'colsample_bytree': 0.9417799976499887, 
                    'reg_alpha': 4.766081395540318e-06,
                    'reg_lambda': 1.0193028680619835e-08}

default_params = {
        "random_state": 42,
        "eval_metric": "logloss",
        "tree_method": "hist",   
        "verbosity": 0,
        "device":'cuda',
}

In [10]:
from xgboost import XGBClassifier

model = XGBClassifier(
    **tuned_xgb_params,
    **default_params
)

model_pipeline = Pipeline([
    ('prep', preprocessor),
    ('model',model)
])

In [11]:
#Training on whole training set to see if it makes any difference 
model_pipeline.fit(X, y)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('prep',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  Pipeline(steps=[('encoder',
                                                                   OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                  unknown_value=-1))]),
                                                  ['common[0].Mn',
                                                   'common[0].Md',
                                                   'common[0].Opt',
                                                   'common[0].Vr',
                                                   'common[0].SN'])])),
                ('model',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_byleve...
                               gamma=2.2246104780594558, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None,
                               learning_rate=0.036989524346778366, max_bin=None,
                               max_cat_threshold=None, max_cat_to_onehot=None,
                               max_delta_step=None, max_depth=12,
                               max_leaves=None, min_child_weight=4, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=2382, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [12]:
#clearing up memory since the dataset is huge
del X,y
gc.collect()
print("Memory cleared!")

Memory cleared!

## Making predictions on test data:

In [13]:
test_path = '/kaggle/input/competitions/cyber-physical-anomaly-detection-for-der-systems/test.csv'

test_df = pl.read_csv(test_path)
print('Test set: ', test_df.shape)
display(test_df.head(3))

Test set:  (1012785, 724)

shape: (3, 724)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Id      ┆ common[0]. ┆ common[0] ┆ common[0] ┆ … ┆ DERMeasur ┆ DERMeasur ┆ DERMeasur ┆ DERMeasur │
│ ---     ┆ ID         ┆ .L        ┆ .Mn       ┆   ┆ eDC[0].Pr ┆ eDC[0].Pr ┆ eDC[0].Pr ┆ eDC[0].Pr │
│ i64     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ t[1].DCW  ┆ t[1].DCWh ┆ t[1].DCWh ┆ t[1].Tmp  │
│         ┆ f64        ┆ f64       ┆ str       ┆   ┆ ---       ┆ Inj       ┆ Abs       ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆ f64       ┆ ---       ┆ ---       ┆ f64       │
│         ┆            ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 3000576 ┆ 1.0        ┆ 66.0      ┆ DERSec    ┆ … ┆ 31410.0   ┆ null      ┆ null      ┆ 23.0      │
│ 356192  ┆ 1.0        ┆ 66.0      ┆ DERSec    ┆ … ┆ 711.0     ┆ null      ┆ null      ┆ 23.0      │
│ 1757012 ┆ 1.0        ┆ 66.0      ┆ DERSec    ┆ … ┆ 4558.0    ┆ null      ┆ null      ┆ 23.0      │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
cols_to_remove = unique_count_1_cols + cols_to_drop + ['Id']
X_test = test_df.drop(cols_to_remove)

In [15]:
y_test_proba = model_pipeline.predict_proba(X_test)[:,1]

best_thresh = 0.12 #this was found out while tuning hyperparameters using optuna
y_preds = (y_test_proba > best_thresh).astype(int)

In [16]:
submission = pl.DataFrame({
    "Id": test_df['Id'],
    "Label": y_preds
})

submission.write_csv("submission.csv")